# Generated by Django 3.0.1 on 2019-12-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codInt', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('vestuario', models.BooleanField()),
                ('iluminacion', models.BooleanField()),
                ('cespedSint', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('fecha_reserva', models.DateField(auto_now_add=True)),
                ('fecha_turno', models.DateTimeField()),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Cancha')),
            ],
        ),
    ]
