# Generated by Django 3.0.1 on 2019-12-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191218_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='empleado',
            field=models.CharField(default='', max_length=50),
        ),
    ]
